"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emissary_client_sdk.types import BaseModel
from emissary_client_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CancelTrainingJobByIDGlobalsTypedDict(TypedDict):
    project_id: NotRequired[str]


class CancelTrainingJobByIDGlobals(BaseModel):
    project_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None


class CancelTrainingJobByIDRequestTypedDict(TypedDict):
    training_job_id: str
    r"""The ID of the training job to cancel"""
    project_id: NotRequired[str]


class CancelTrainingJobByIDRequest(BaseModel):
    training_job_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the training job to cancel"""

    project_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
